from tkinter import *

def calculo():
    lista = list()
    lista.extend([int(qntd_resposta1.get()),int(qntd_resposta2.get()),int(qntd_resposta3.get()),int(qntd_resposta4.get()),int(qntd_resposta5.get()),
    int(qntd_resposta6.get()),int(qntd_resposta7.get()),int(qntd_resposta8.get()),int(qntd_resposta9.get()),int(qntd_resposta10.get())])
    soma = sum(lista)
    janela_result.config(text=f'{soma}')

janela = Tk()
janela.geometry('300x320')
janela.title('Calculadora de peças')
nomePeça = Label(janela, text='TIPO DE PEÇA').place(x=29, y=11)

resposta1 = Entry(janela).place(x=10, y=30)
resposta2 = Entry(janela).place(x=10, y=51)
resposta3 = Entry(janela).place(x=10, y=72)
resposta4 = Entry(janela).place(x=10, y=93)
resposta5 = Entry(janela).place(x=10, y=114)
resposta6 = Entry(janela).place(x=10, y=135)
resposta7 = Entry(janela).place(x=10, y=156)
resposta8 = Entry(janela).place(x=10, y=177)
resposta9 = Entry(janela).place(x=10, y=198)
resposta10 = Entry(janela).place(x=10, y=219)

espaço_vazio = Label(janela).place(x=10, y=240)

escrita_resultado = Label(janela, text=' TOTAL DE PEÇAS: ').place(x=10, y=282)
qntd_peça = Label(janela, text='QUANTIDADE').place(x=180, y=11)
qntd_resposta1 = Entry(janela)
qntd_resposta1.place(x=161, y=30)
qntd_resposta2 = Entry(janela)
qntd_resposta2.place(x=161, y=51)
qntd_resposta3 = Entry(janela)
qntd_resposta3.place(x=161, y=72)
qntd_resposta4 = Entry(janela)
qntd_resposta4.place(x=161, y=93)
qntd_resposta5 = Entry(janela)
qntd_resposta5.place(x=161, y=114)
qntd_resposta6 = Entry(janela)
qntd_resposta6.place(x=161, y=135)
qntd_resposta7 = Entry(janela)
qntd_resposta7.place(x=161, y=156)
qntd_resposta8 = Entry(janela)
qntd_resposta8.place(x=161, y=177)
qntd_resposta9 = Entry(janela)
qntd_resposta9.place(x=161, y=198)
qntd_resposta10 = Entry(janela)
qntd_resposta10.place(x=161, y=219)
botão = Button(janela, text='CALCULAR', command=calculo).place(x=112, y=242)
janela_result = Label(janela, text='')
janela_result.place(x=180, y=282)

janela.mainloop()
